# Generated by Django 3.0.5 on 2020-05-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('dis_history', models.CharField(max_length=30)),
                ('current_disease', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=20)),
                ('phone_num', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=50)),
                ('City', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='data')),
            ],
        ),
    ]
