# Generated by Django 3.0.5 on 2020-05-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=300, unique=True)),
                ('lname', models.CharField(max_length=300, unique=True)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('birthday', models.CharField(max_length=300, unique=True)),
                ('password', models.CharField(max_length=30, unique=True)),
                ('cpassword', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
