# Generated by Django 3.0.5 on 2020-05-11 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Reg',
        ),
    ]
