# Generated by Django 3.0.5 on 2020-05-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changepassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldp', models.CharField(max_length=30, unique=True)),
                ('newp', models.CharField(max_length=30, unique=True)),
                ('retypep', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
