# Generated by Django 3.0.5 on 2020-05-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_changepassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300, unique=True)),
                ('txtarea', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
