# Generated by Django 3.0.5 on 2020-05-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='license_no',
        ),
    ]
