# Generated by Django 3.0.5 on 2020-05-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20200512_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
