# Generated by Django 3.0.6 on 2020-06-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20200527_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='name',
            new_name='user_email',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_phn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
