# Generated by Django 3.0.6 on 2020-06-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20200609_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changepassword',
            name='newp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='changepassword',
            name='oldp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='changepassword',
            name='retypep',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hands',
            name='subject',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hands',
            name='txtarea',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='login',
            name='user',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reg',
            name='birthday',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reg',
            name='cpassword',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reg',
            name='fname',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reg',
            name='lname',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reg',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=300),
        ),
    ]
